name = "Raramur: Admire & Create"
author = "lottuce_yami"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d107da5d56d2284995d05bc8857d7b7ba41d608ecf06ce7f91adb8ae15cd6ac"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
