name = "Raramur: Admire & Create"
author = "lottuce_yami"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8850b504b8722bf965a74dc2bdb70d184b227fd29e08f510809225a770e44a23"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
