name = "Raramur: Admire & Create"
author = "lottuce_yami"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca65ef206c566f3bfb26c57165a14801171d66a855e907b617a6fbe59e4b7da5"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
