name = "Raramur: Admire & Create"
author = "lottuce_yami"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6607d7b1a7535a1f65ac209af27af6ce8c4a44f2df970bed018cc2ad1c61215e"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
