name = "Raramur: Admire & Create"
author = "lottuce_yami"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8232287563a9d2c8e87534befb93aaeac3576ffdcd1872a1daa4a655d7a69971"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
