name = "Raramur: Admire & Create"
author = "lottuce_yami"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e03ff736bd7ba923359a2d7e0800acb464e5d1cdbfccbfb5e655ce2091fcb07e"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
