name = "Raramur: Admire & Create"
author = "lottuce_yami"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fb008b1a77309956d749726684c2ddcf98cc8be24b743e03cb764b8df442db1"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
